
const backToCartButton = document.getElementById('back-to-cart-button')


//Login
const checkoutLoginScreen = document.getElementById('checkout-login-screen')
const loginEmailField = document.getElementById('login-email-field')
const loginPasswordField = document.getElementById('login-password-field')
const forgotPasswordButton = document.getElementById('forgot-password-button')
const loginButton = document.getElementById('login-button')
const loginAppleButton = document.getElementById('login-apple-button')
const loginGoogleButton = document.getElementById('login-google-button')
const guestLoginButton = document.getElementById('guest-login-button')

//___________________________________Guest Checkout__________________________________________
const guestCheckoutScreen = document.getElementById('guest-checkout-screen')
const orderSummaryItemsContainer = document.getElementById('order-summary-items-container')
const orderSubtotal = document.getElementById('order-subtotal')
const orderShippingPrice = document.getElementById('order-shipping-price')
const orderTax = document.getElementById('order-tax')
const orderTotal = document.getElementById('order-total')

//Delivery Screen
const orderDeliveryFormBlock = document.getElementById('order-delivery-form-block')
const shippingFirstNameField = document.getElementById('shipping-first-name-field')
const shippingFirstNameError = document.getElementById('shipping-first-name-error')
const shippingLastNameField = document.getElementById('shipping-last-name-field')
const shippingLastNameError = document.getElementById('shipping-last-name-error')
const shippingAddressField = document.getElementById('shipping-address-field')
const shippingAddressError = document.getElementById('shipping-address-error')
const shippingAddressAddSecond = document.getElementById('shipping-address-add-second')
const shippingAddressSecondField = document.getElementById('shipping-address-second-field')
const shippingCityField = document.getElementById('shipping-city-field')
const shippingCityError = document.getElementById('shipping-city-error')
const shippingStateDropdown = document.getElementById('shipping-state-dropdown')
const shippingStateDropdownText = document.getElementById('shipping-state-dropdown-text')
const shippingStateDropdownChevron = document.getElementById('shipping-state-dropdown-chevron')
const shippingStateDropdownOptions = document.getElementById('shipping-state-dropdown-options')
const shippingStateError = document.getElementById('shipping-state-error')
const shippingZipField = document.getElementById('shipping-zip-field')
const shippingZipError = document.getElementById('shipping-zip-error')
const shippingAddressCheckbox = document.getElementById('shipping-address-checkbox')
const contactEmailField = document.getElementById('contact-email-field')
const contactEmailError = document.getElementById('contact-email-error')
const contactPhoneField = document.getElementById('contact-phone-field')
const contactPhoneError = document.getElementById('contact-phone-error')
const textUpdatesCheckbox = document.getElementById('text-updates-checkbox')
const continueToPaymentButton = document.getElementById('continue-to-payment-button')

//Payment Screen
const orderPaymentFormBlock = document.getElementById('order-payment-form-block')
const orderPaymentBack = document.getElementById('order-payment-back')
const creditCardField = document.getElementById('credit-card-field')
const creditCardFieldError = document.getElementById('credit-card-field-error')
const expirationMonthDropdown = document.getElementById('expiration-month-dropdown')
const expirationMonthDropdownText = document.getElementById('expiration-month-dropdown-text')
const expirationMonthDropdownChevron = document.getElementById('expiration-month-chevron')
const expirationMonthDropdownOptions = document.getElementById('expiration-month-dropdown-options')
const expirationMonthError = document.getElementById('expiration-month-error')
const expirationYearDropdown = document.getElementById('expiration-year-dropdown')
const expirationYearDropdownText = document.getElementById('expiration-year-dropdown-text')
const expirationYearDropdownChevron = document.getElementById('expiration-year-chevron')
const expirationYearDropdownOptions = document.getElementById('expiration-year-dropdown-options')
const expirationYearError = document.getElementById('expiration-year-error')
const cvcField = document.getElementById('cvc-field')
const cvcFieldError = document.getElementById('cvc-field-error')
const paymentOptionsButton = document.getElementById('payment-options-button')
const paymentOptionsContainer = document.getElementById('payment-options-container')
const paypalButton = document.getElementById('paypal-button')
const venmoButton = document.getElementById('venmo-button')
const applePayButton = document.getElementById('apple-pay-button')
const billingPrefilledName = document.getElementById('billing-prefilled-name')
const billingPrefilledAddress = document.getElementById('billing-prefilled-address')
const billingPrefilledAddress2 = document.getElementById('billing-prefilled-address-2')
const billingPrefilledCity = document.getElementById('billing-prefilled-city')
const billingPrefilledChange = document.getElementById('billing-prefilled-change')
const billingAddressContainer = document.getElementById('billing-address-container')
const billingFirstField = document.getElementById('billing-first-field')
const billingFirstError = document.getElementById('billing-first-error')
const billingLastField = document.getElementById('billing-last-field')
const billingLastError = document.getElementById('billing-last-error')
const billingAddressField = document.getElementById('billing-address-field')
const billingAddressError = document.getElementById('billing-address-error')
const billingAddressAddSecond = document.getElementById('billing-address-add-second')
const biillingAddressSecond = document.getElementById('billing-address-second')
const billingCityField = document.getElementById('billing-city-field')
const billingCityError = document.getElementById('billing-city-error')
const billingStateDropdown = document.getElementById('billing-state-dropdown')
const billingStateText = document.getElementById('billing-state-text')
const billingStateChevron = document.getElementById('billing-state-chevron')
const billingStateDropdownOptions = document.getElementById('billing-state-dropdown-options')
const billingStateError = document.getElementById('billing-state-error')
const billingZipField = document.getElementById('billing-zip-field')
const billingZipError = document.getElementById('billing-zip-error')
const placeOrderButton = document.getElementById('place-order-button')

